import type { OutputKind, PlatformHint, RuntimeSettingsForm } from "./types";

export const OUTPUTS: OutputKind[] = ["audio", "video", "image", "page_html"];
export const TERMINAL = new Set(["ready", "error", "candidates_ready", "needs_profile"]);
export const PAGE_SIZE_OPTIONS = [3, 5, 10, 20, 50];
export const LOGIN_TARGETS = [
  { id: "douyin", label: "抖音", url: "https://www.douyin.com/" },
  { id: "kuaishou", label: "快手", url: "https://www.kuaishou.com/" },
  { id: "bilibili", label: "哔哩哔哩", url: "https://www.bilibili.com/" },
  { id: "youtube", label: "YouTube", url: "https://www.youtube.com/" },
  { id: "soundcloud", label: "SoundCloud", url: "https://soundcloud.com/" },
  { id: "ximalaya", label: "喜马拉雅", url: "https://www.ximalaya.com/" },
  { id: "tiktok", label: "TikTok", url: "https://www.tiktok.com/" },
  { id: "vimeo", label: "Vimeo", url: "https://vimeo.com/" },
  { id: "weibo", label: "微博", url: "https://weibo.com/" },
  { id: "dailymotion", label: "Dailymotion", url: "https://www.dailymotion.com/" },
  { id: "rumble", label: "Rumble", url: "https://rumble.com/" },
  { id: "peertube", label: "PeerTube", url: "https://video.blender.org/" },
  { id: "archive_org", label: "Archive.org", url: "https://archive.org/" },
  { id: "wayback", label: "Wayback", url: "https://web.archive.org/" },
  { id: "archive_it", label: "Archive-It", url: "https://archive-it.org/" },
  { id: "perma_cc", label: "Perma.cc", url: "https://perma.cc/" },
  { id: "archive_today", label: "archive.today", url: "https://archive.today/" },
  { id: "ghostarchive", label: "Ghostarchive", url: "https://ghostarchive.org/" },
  { id: "webcitation", label: "WebCitation", url: "https://www.webcitation.org/" },
  { id: "memento", label: "Memento", url: "https://timetravel.mementoweb.org/" },
  { id: "wikimedia", label: "Wikimedia", url: "https://commons.wikimedia.org/" },
  { id: "twitch", label: "Twitch", url: "https://www.twitch.tv/" },
  { id: "twitter", label: "X / Twitter", url: "https://x.com/" },
  { id: "reddit", label: "Reddit", url: "https://www.reddit.com/" },
  { id: "instagram", label: "Instagram", url: "https://www.instagram.com/" },
  { id: "facebook", label: "Facebook", url: "https://www.facebook.com/watch/" },
  { id: "pinterest", label: "Pinterest", url: "https://www.pinterest.com/" },
  { id: "imgur", label: "Imgur", url: "https://imgur.com/" },
  { id: "flickr", label: "Flickr", url: "https://www.flickr.com/" },
  { id: "bandcamp", label: "Bandcamp", url: "https://bandcamp.com/" },
  { id: "mixcloud", label: "Mixcloud", url: "https://www.mixcloud.com/" },
  { id: "niconico", label: "Niconico", url: "https://www.nicovideo.jp/" },
  { id: "youku", label: "优酷", url: "https://www.youku.com/" },
  { id: "iqiyi", label: "爱奇艺", url: "https://www.iqiyi.com/" },
  { id: "acfun", label: "AcFun", url: "https://www.acfun.cn/" },
  { id: "maccms", label: "资源站", url: "https://www.dmttang.com/" },
];

export const EMPTY_RUNTIME_FORM: RuntimeSettingsForm = {
  public_base_url: "",
  max_download_mb: "",
  download_timeout_seconds: "",
  yt_dlp_timeout_seconds: "",
  yt_dlp_max_json_mb: "",
  job_ttl_hours: "",
  page_archive_max_resources: "",
  page_archive_max_resource_mb: "",
  page_archive_max_total_mb: "",
  page_archive_capture_cdp_enabled: true,
  page_archive_save_mhtml_enabled: true,
  page_archive_save_har_enabled: true,
  page_archive_save_warc_enabled: true,
  page_archive_cdp_body_max_mb: "",
  page_archive_cdp_body_total_mb: "",
  cache_cleanup_min_age_hours: "",
};

export const FALLBACK_PLATFORM_HINTS: PlatformHint[] = [
  "auto",
  "bilibili",
  "youtube",
  "soundcloud",
  "ximalaya",
  "douyin",
  "kuaishou",
  "pornhub",
  "acfun",
  "iqiyi",
  "youku",
  "tiktok",
  "vimeo",
  "weibo",
  "dailymotion",
  "rumble",
  "peertube",
  "archive_org",
  "wayback",
  "archive_it",
  "perma_cc",
  "archive_today",
  "ghostarchive",
  "webcitation",
  "memento",
  "wikimedia",
  "twitch",
  "twitter",
  "reddit",
  "instagram",
  "facebook",
  "pinterest",
  "imgur",
  "flickr",
  "bandcamp",
  "mixcloud",
  "niconico",
  "fc2",
  "spotify",
  "live",
  "generic",
];

export const WEB_ARCHIVE_PLATFORM_HINTS = new Set<PlatformHint>([
  "wayback",
  "archive_it",
  "perma_cc",
  "archive_today",
  "ghostarchive",
  "webcitation",
  "memento",
]);
